/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zola.views;

import com.zola.event.PublicEvent;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;



public class Menu_Right extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Left
     */
//    private final Model_User_Account user;
//    public Model_User_Account getUser() {
//        return user;
//    }
    public Menu_Right() {
        initComponents();
//        this.user=user;
//        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource(user.getAvatarPath())));
    }
//    
//    public void init(){
//        if(Service.getInstance().getUser().getDescription()==null){
//            txt_description.setText("\"Description Here\"");
//        } else txt_description.setText("\"" + Service.getInstance().getUser().getDescription() + "\"");
//    }

    protected void paintChildren(Graphics grphcs){
        Graphics2D g2d = (Graphics2D)grphcs;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gdp = new GradientPaint(0,0,Color.decode("#80E2FF"),0,getHeight(),Color.decode("#9E74D0"));
        g2d.setPaint(gdp);
        g2d.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
        g2d.fillRect(0, getWidth()-20, getWidth(), getHeight());
        setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        super.paintChildren(grphcs);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new com.zola.swing.ImageAvatar();
        btn_change_avatar = new javax.swing.JLabel();
        txt_user_gender = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_change_des = new javax.swing.JLabel();
        txt_description = new javax.swing.JLabel();
        txt_current_user = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        imageAvatar1.setBorderColor(new java.awt.Color(126, 226, 255));
        imageAvatar1.setBorderSize(2);
        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/zola/icon/profileTest.jpg"))); // NOI18N
        imageAvatar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageAvatar1MouseClicked(evt);
            }
        });
        imageAvatar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_change_avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zola/icon/camera.png"))); // NOI18N
        btn_change_avatar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_change_avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_change_avatarMousePressed(evt);
            }
        });
        imageAvatar1.add(btn_change_avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        txt_user_gender.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txt_user_gender.setForeground(new java.awt.Color(255, 255, 255));
        txt_user_gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_logout.setBackground(new java.awt.Color(158, 72, 192));
        btn_logout.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Log out");
        btn_logout.setBorderPainted(false);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_change_des.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zola/icon/edit-des.png"))); // NOI18N
        btn_change_des.setLabelFor(txt_description);
        btn_change_des.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_change_des.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_change_desMousePressed(evt);
            }
        });

        txt_description.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_description.setForeground(new java.awt.Color(255, 255, 255));
        txt_description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_description.setText("\"Description Here\"");
        txt_description.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txt_description.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txt_current_user.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        txt_current_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_current_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_user_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_current_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn_change_des)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_current_user, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_user_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_change_des)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        txt_description.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
       
       int isLogout;
        isLogout = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Log out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
       if(isLogout == JOptionPane.YES_OPTION){
            PublicEvent.getInstance().getEventMain().logout();  
            
       } else {
           return;
       }
       
           
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void imageAvatar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar1MouseClicked
       
    }//GEN-LAST:event_imageAvatar1MouseClicked

    private void btn_change_avatarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_change_avatarMousePressed
         JFileChooser src = new JFileChooser();
                    //filter image file
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image File", "png", "jpg", "jpeg");
        src.setFileFilter(filter);
        int val = src.showOpenDialog(null);
                    if (val == JFileChooser.APPROVE_OPTION){
                        String path = src.getSelectedFile().toString();
                        ImageIcon image = new ImageIcon(path);
                        imageAvatar1.setImage(image);
                        //Service.getInstance().getUser().setAvatarPath(path);
                    }
                    else return;
    }//GEN-LAST:event_btn_change_avatarMousePressed

    private void btn_change_desMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_change_desMousePressed
        JTextArea txa_Description = new javax.swing.JTextArea();
        txa_Description.setColumns(20);
        txa_Description.setRows(4);
        txa_Description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                 int max = 38;
                    if(txa_Description.getText().length() > max+1) {
                         evt.consume();
                         String shortened = txa_Description.getText().substring(0, max);
                         txa_Description.setText(shortened);
                    }else if(txa_Description.getText().length() > max) {
                         evt.consume();
                   }
                 }
         });
        
        int des_change = JOptionPane.showConfirmDialog(null, txa_Description, "Description", JOptionPane.YES_NO_OPTION);
        
        if(des_change==JOptionPane.YES_OPTION){
            if(txa_Description.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please input description!!", "Information",
                        JOptionPane.INFORMATION_MESSAGE);
            } else{
                  txt_description.setText("\"" + txa_Description.getText() + "\"");
                 
            }
        } else return;
    
    }//GEN-LAST:event_btn_change_desMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_change_avatar;
    private javax.swing.JLabel btn_change_des;
    private javax.swing.JButton btn_logout;
    public static com.zola.swing.ImageAvatar imageAvatar1;
    public static javax.swing.JLabel txt_current_user;
    public static javax.swing.JLabel txt_description;
    public static javax.swing.JLabel txt_user_gender;
    // End of variables declaration//GEN-END:variables
}
